version: "3.1"
services:
  postgres_db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "dev"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    restart: always
    container_name: server
    build:
      context: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/uploads
    command: yarn start:dev
    depends_on:
      - postgres_db

  client:
    build:
      context: ./client/
    container_name: client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  pgdata:
    driver: local
