version: "3.1"
services:
  postgres_db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "dev"
    volumes:
      - ./db/dev/data:/var/lib/postgresql/data

  server:
    restart: always
    container_name: server
    build:
      context: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/uploads
    command: yarn start:dev
    depends_on:
      - postgres_db

  client:
    build:
      context: ./client/
    container_name: client
    stdin_open: true
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # create-ui-app <= 5.x
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3001
    depends_on:
      - server
